version:2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:10.6
      - image: circleci/mongo:4.0
    steps:
      - checkout
      - run: npm install
      - run: npm test